server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: dev

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"
  endpoint:
    health:
      show-details: always