server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  
  data:
    mongodb:
      # Try without authentication first
      uri: mongodb://localhost:27017/dominos
      # If authentication is needed, use this:
      # uri: mongodb://admin:password123@localhost:27017/dominos?authSource=admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      password: redispassword123
      timeout: 2000ms
      
  cache:
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

jwt:
  secret: dominos-secret-key-for-jwt-token-generation-very-long-key-must-be-at-least-256-bits
  access-token-expiration: 3600000  # 1 hour
  refresh-token-expiration: 604800000  # 7 days

logging:
  level:
    com.dominos.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method