server:
  port: 8081

spring:
  application:
    name: user-service
  profiles:
    active: dev
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/dominos
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      
  cache:
    redis:
      time-to-live: 3600000
      cache-null-values: false

jwt:
  secret: dominos-secret-key-for-jwt-token-generation-very-long-key-must-be-at-least-256-bits
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

logging:
  level:
    com.dominos.user: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html